# Generated by Django 6.0.4 on 2026-04-23 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='NDEReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('report_type', models.CharField(choices=[('UT', 'UT — Ultrasonic Testing'), ('MT', 'MT — Magnetic Particle Testing'), ('PT', 'PT — Penetrant Testing'), ('VT', 'VT — Visual Testing'), ('RT', 'RT — Radiographic Testing'), ('Other', 'Other')], db_index=True, default='UT', max_length=20)),
                ('section', models.CharField(blank=True, db_index=True, help_text='e.g. AX, CX, BX', max_length=100)),
                ('report_file', models.FileField(max_length=500, upload_to='nde_reports/')),
                ('notes', models.TextField(blank=True, help_text='Optional notes, keywords, or summary for searching')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('uploaded_by', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
