"""
package_portable.py — Build script for creating a self-contained portable
deployment package of the TVA Barkley Weld Inspection app.

Run this on your dev machine (Windows, Mac, or Linux) to produce a folder
that can be copied to a USB drive and run on any Windows PC.

Usage:
    python scripts/package_portable.py --output E:\\TVA-Weld-Inspector
    python scripts/package_portable.py --output /tmp/TVA-Weld-Inspector --python-version 3.12.8

The script:
  1. Downloads the Python 3.12 embeddable package (Windows amd64)
  2. Extracts it to <output>/python/
  3. Downloads and installs pip into the embedded Python
  4. Enables site-packages by uncommenting `import site` in python312._pth
  5. Installs Django, Pillow, openpyxl, reportlab, whitenoise into the
     embedded Python's site-packages
  6. Copies the Django project into <output>/app/
  7. Copies db.sqlite3 if it exists
  8. Copies media/ directory if it exists
  9. Runs collectstatic using the embedded Python
 10. Creates the superuser setup script at <output>/app/create_user.py
 11. Copies the START.bat, STOP.bat, SETUP_USER.bat launcher scripts
 12. Copies README_PORTABLE.md as README.txt
"""

import argparse
import os
import platform
import shutil
import subprocess
import sys
import urllib.request
import zipfile
from pathlib import Path

# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def log(msg: str) -> None:
    print(f"[package_portable] {msg}")


def download_file(url: str, dest: Path) -> None:
    """Download *url* to *dest*, showing a simple progress indicator."""
    # Only allow downloads from trusted domains
    trusted_prefixes = (
        "https://www.python.org/",
        "https://bootstrap.pypa.io/",
    )
    if not any(url.startswith(prefix) for prefix in trusted_prefixes):
        sys.exit(f"Refusing to download from untrusted URL: {url}")
    log(f"Downloading {url}")
    with urllib.request.urlopen(url) as response:  # noqa: S310
        total = int(response.headers.get("Content-Length", 0))
        downloaded = 0
        chunk_size = 65536
        with open(dest, "wb") as f:
            while True:
                chunk = response.read(chunk_size)
                if not chunk:
                    break
                f.write(chunk)
                downloaded += len(chunk)
                if total:
                    pct = downloaded * 100 // total
                    print(f"\r  {pct}% ({downloaded // 1024} KB / {total // 1024} KB)  ", end="", flush=True)
    print()  # newline after progress
    log(f"Saved to {dest}")


def run(cmd: list, cwd: Path | None = None, env: dict | None = None) -> None:
    """Run a subprocess command and raise on failure."""
    log(f"Running: {' '.join(str(c) for c in cmd)}")
    result = subprocess.run(cmd, cwd=cwd, env=env)
    if result.returncode != 0:
        sys.exit(f"Command failed with exit code {result.returncode}: {' '.join(str(c) for c in cmd)}")


# ---------------------------------------------------------------------------
# Directories to copy from the Django project
# ---------------------------------------------------------------------------

# Relative to the Django project root (where manage.py lives)
_PROJECT_DIRS = [
    "weldmap",
    "welds",
    "gallery",
]

_PROJECT_FILES = [
    "manage.py",
]

# Patterns to exclude when copying the project
_EXCLUDE_PATTERNS = {
    "__pycache__",
    "*.pyc",
    "*.pyo",
    ".git",
    ".env",
    "staticfiles",  # will be re-generated by collectstatic
}


def _should_exclude(path: Path) -> bool:
    name = path.name
    if name in _EXCLUDE_PATTERNS:
        return True
    if name.endswith(".pyc") or name.endswith(".pyo"):
        return True
    return False


def copy_tree(src: Path, dst: Path) -> None:
    """Recursively copy src to dst, skipping excluded patterns."""
    dst.mkdir(parents=True, exist_ok=True)
    for item in src.iterdir():
        if _should_exclude(item):
            continue
        target = dst / item.name
        if item.is_dir():
            copy_tree(item, target)
        else:
            shutil.copy2(item, target)


# ---------------------------------------------------------------------------
# Main build logic
# ---------------------------------------------------------------------------

def build(output_dir: Path, python_version: str) -> None:
    # Locate the repo root (the directory containing manage.py)
    script_dir = Path(__file__).resolve().parent
    repo_root = script_dir.parent

    if not (repo_root / "manage.py").exists():
        sys.exit(f"Cannot find manage.py in {repo_root}. Is this script in the scripts/ subdirectory?")

    log(f"Repo root  : {repo_root}")
    log(f"Output dir : {output_dir}")
    log(f"Python ver : {python_version}")

    output_dir = output_dir.resolve()
    output_dir.mkdir(parents=True, exist_ok=True)

    python_dir = output_dir / "python"
    app_dir = output_dir / "app"

    # ------------------------------------------------------------------
    # Step 1-2: Download and extract the embeddable Python package
    # ------------------------------------------------------------------
    embed_zip_name = f"python-{python_version}-embed-amd64.zip"
    embed_url = f"https://www.python.org/ftp/python/{python_version}/{embed_zip_name}"
    embed_zip_path = output_dir / embed_zip_name

    if not embed_zip_path.exists():
        download_file(embed_url, embed_zip_path)
    else:
        log(f"Embeddable zip already exists, skipping download: {embed_zip_path}")

    if python_dir.exists():
        log(f"Removing existing python dir: {python_dir}")
        shutil.rmtree(python_dir)

    log(f"Extracting {embed_zip_path} → {python_dir}")
    with zipfile.ZipFile(embed_zip_path, "r") as zf:
        zf.extractall(python_dir)

    # ------------------------------------------------------------------
    # Step 4: Enable site-packages in the embedded Python
    # ------------------------------------------------------------------
    # The embeddable package ships with a python3xx._pth file that has
    # `#import site` commented out. Uncommenting it enables pip/site-packages.
    major, minor = python_version.split(".")[:2]
    pth_file = python_dir / f"python{major}{minor}._pth"
    if not pth_file.exists():
        # Try alternate names
        for f in python_dir.glob("python*._pth"):
            pth_file = f
            break

    if pth_file.exists():
        content = pth_file.read_text(encoding="utf-8")
        new_content = content.replace("#import site", "import site")
        if new_content != content:
            pth_file.write_text(new_content, encoding="utf-8")
            log(f"Enabled site-packages in {pth_file.name}")
        else:
            log(f"site-packages already enabled in {pth_file.name}")
    else:
        log("WARNING: Could not find ._pth file — site-packages may not be enabled")

    # ------------------------------------------------------------------
    # Step 3: Download and install pip
    # ------------------------------------------------------------------
    get_pip_path = output_dir / "get-pip.py"
    if not get_pip_path.exists():
        download_file("https://bootstrap.pypa.io/get-pip.py", get_pip_path)
    else:
        log("get-pip.py already exists, skipping download")

    python_exe = python_dir / "python.exe"
    run([python_exe, str(get_pip_path), "--no-warn-script-location"])

    # ------------------------------------------------------------------
    # Step 5: Install portable dependencies
    # ------------------------------------------------------------------
    portable_reqs = repo_root / "requirements-portable.txt"
    if portable_reqs.exists():
        run([
            python_exe, "-m", "pip", "install",
            "-r", str(portable_reqs),
            "--no-warn-script-location",
        ])
    else:
        # Fallback: install individually
        packages = ["Django>=4.2", "Pillow>=10.0.0", "openpyxl>=3.1.2", "reportlab>=4.2.0", "whitenoise>=6.6.0"]
        run([python_exe, "-m", "pip", "install", "--no-warn-script-location"] + packages)

    # ------------------------------------------------------------------
    # Step 6: Copy the Django project into <output>/app/
    # ------------------------------------------------------------------
    if app_dir.exists():
        log(f"Removing existing app dir: {app_dir}")
        shutil.rmtree(app_dir)
    app_dir.mkdir(parents=True)

    for fname in _PROJECT_FILES:
        src = repo_root / fname
        if src.exists():
            shutil.copy2(src, app_dir / fname)
            log(f"Copied {fname}")

    for dname in _PROJECT_DIRS:
        src = repo_root / dname
        if src.exists():
            copy_tree(src, app_dir / dname)
            log(f"Copied directory {dname}/")
        else:
            log(f"WARNING: directory {dname}/ not found in repo root")

    # ------------------------------------------------------------------
    # Step 7: Copy db.sqlite3 if it exists
    # ------------------------------------------------------------------
    sqlite_src = repo_root / "db.sqlite3"
    if sqlite_src.exists():
        shutil.copy2(sqlite_src, app_dir / "db.sqlite3")
        log("Copied db.sqlite3")
    else:
        log("db.sqlite3 not found — a fresh database will be created on first run")

    # ------------------------------------------------------------------
    # Step 8: Copy media/ directory if it exists
    # ------------------------------------------------------------------
    media_src = repo_root / "media"
    if media_src.exists():
        log("Copying media/ directory (this may take a while for large photo libraries)…")
        copy_tree(media_src, app_dir / "media")
        log("Copied media/")
    else:
        log("media/ directory not found — skipping")

    # ------------------------------------------------------------------
    # Step 9: Run collectstatic
    # ------------------------------------------------------------------
    env = os.environ.copy()
    env["PORTABLE_MODE"] = "1"
    env["DJANGO_SETTINGS_MODULE"] = "weldmap.settings"
    # Suppress the prompt
    run(
        [python_exe, "manage.py", "collectstatic", "--noinput"],
        cwd=app_dir,
        env=env,
    )
    log("collectstatic complete")

    # ------------------------------------------------------------------
    # Step 10: Create create_user.py helper script
    # ------------------------------------------------------------------
    create_user_script = app_dir / "create_user.py"
    create_user_script.write_text(
        '"""Helper script to create a Django superuser interactively."""\n'
        "import os\n"
        "import django\n\n"
        'os.environ.setdefault("DJANGO_SETTINGS_MODULE", "weldmap.settings")\n'
        'os.environ["PORTABLE_MODE"] = "1"\n'
        "django.setup()\n\n"
        "from django.contrib.auth.management.commands.createsuperuser import Command\n"
        "from django.core.management import call_command\n\n"
        'call_command("createsuperuser")\n',
        encoding="utf-8",
    )
    log("Created create_user.py")

    # ------------------------------------------------------------------
    # Step 11: Copy batch files and README
    # ------------------------------------------------------------------
    scripts_dir = repo_root / "scripts"
    for bat_file in ["START.bat", "STOP.bat", "SETUP_USER.bat"]:
        src = scripts_dir / bat_file
        if src.exists():
            shutil.copy2(src, output_dir / bat_file)
            log(f"Copied {bat_file}")
        else:
            log(f"WARNING: {bat_file} not found in scripts/")

    readme_src = repo_root / "README_PORTABLE.md"
    if readme_src.exists():
        shutil.copy2(readme_src, output_dir / "README.txt")
        log("Copied README_PORTABLE.md → README.txt")

    # ------------------------------------------------------------------
    # Done
    # ------------------------------------------------------------------
    log("")
    log("=" * 60)
    log("Portable package build complete!")
    log(f"Output folder: {output_dir}")
    log("")
    log("To distribute:")
    log("  1. Copy the entire output folder to a USB drive")
    log("  2. On the customer's PC, double-click START.bat")
    log("  3. To create the first login, double-click SETUP_USER.bat")
    log("=" * 60)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------

def main() -> None:
    if platform.system() in ("Linux", "Darwin"):
        log("NOTE: Building on Linux/Mac — the output is for Windows only.")
        log("The embedded Python .exe won't run on this machine, but the")
        log("package will work correctly when copied to a Windows PC.")
        log("")

    parser = argparse.ArgumentParser(
        description="Build a self-contained portable Windows package for the TVA Weld Inspector app."
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("TVA-Weld-Inspector"),
        help="Destination folder for the portable package (default: ./TVA-Weld-Inspector)",
    )
    parser.add_argument(
        "--python-version",
        default="3.12.8",
        help="Python embeddable version to download (default: 3.12.8)",
    )
    args = parser.parse_args()

    build(args.output, args.python_version)


if __name__ == "__main__":
    main()
