# Generated by Django 6.0.2 on 2026-02-17 03:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Weld',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report', models.IntegerField()),
                ('side', models.CharField(max_length=50)),
                ('section', models.CharField(db_index=True, max_length=100)),
                ('weld_id', models.CharField(max_length=50)),
                ('weld_id2', models.CharField(blank=True, max_length=50)),
                ('weld_id3', models.CharField(blank=True, max_length=50)),
                ('weld_id4', models.CharField(blank=True, max_length=50)),
                ('estimated_repair_length', models.FloatField(blank=True, null=True)),
                ('total_weld_length', models.FloatField(blank=True, null=True)),
                ('table_6_1_criteria_1', models.CharField(blank=True, max_length=200)),
                ('table_6_1_criteria_2', models.CharField(blank=True, max_length=200)),
                ('table_6_1_criteria_3', models.CharField(blank=True, max_length=200)),
                ('weld_type', models.CharField(blank=True, max_length=100)),
                ('weld_size', models.FloatField(blank=True, null=True)),
                ('wps_number', models.CharField(default='DWPS-SM-Special-B-3-N Rev 0', max_length=100)),
                ('inspection_utsw', models.CharField(blank=True, max_length=50)),
                ('inspection_mt', models.CharField(blank=True, max_length=50)),
                ('inspector', models.CharField(blank=True, max_length=200)),
                ('date', models.DateField(blank=True, null=True)),
                ('pass_fail', models.CharField(blank=True, max_length=20)),
                ('corrective_action_taken', models.CharField(blank=True, max_length=20)),
                ('repair_welder', models.CharField(blank=True, max_length=200)),
                ('repair_inspection_date', models.DateField(blank=True, null=True)),
                ('weld_process', models.CharField(blank=True, max_length=100)),
                ('note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'unique_together': {('section', 'weld_id4')},
            },
        ),
        migrations.CreateModel(
            name='WeldPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='weld_photos/%Y/%m/%d/')),
                ('report_number', models.IntegerField()),
                ('caption', models.CharField(blank=True, max_length=500)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('weld', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photos', to='welds.weld')),
            ],
        ),
    ]
