# Generated by Django 6.0.2 on 2026-02-17 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welds', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weld',
            name='weld_size',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
