# Generated by Django 6.0.2 on 2026-02-21 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welds', '0002_alter_weld_weld_size'),
    ]

    operations = [
        migrations.AlterField(
            model_name='weldphoto',
            name='photo',
            field=models.ImageField(max_length=500, upload_to='weld_photos/%Y/%m/%d/'),
        ),
    ]
