# Generated by Django 6.0.2 on 2026-02-22 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welds', '0003_alter_weldphoto_photo'),
    ]

    operations = [
        migrations.RenameField(
            model_name='weldphoto',
            old_name='caption',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='weldphoto',
            name='weld',
        ),
        migrations.AddField(
            model_name='weldphoto',
            name='original_filename',
            field=models.CharField(default='', max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='weldphoto',
            name='section',
            field=models.CharField(blank=True, db_index=True, max_length=100),
        ),
        migrations.AddField(
            model_name='weldphoto',
            name='subfolder',
            field=models.CharField(blank=True, db_index=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='weldphoto',
            name='report_number',
            field=models.CharField(blank=True, db_index=True, max_length=20),
        ),
    ]
