# Generated by Django 6.0.3 on 2026-03-12 23:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('welds', '0004_rename_caption_weldphoto_description_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='WeldIdKey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=10, unique=True)),
                ('meaning', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['code'],
            },
        ),
    ]
