# Generated by Django 6.0.3 on 2026-03-12 23:01

from django.db import migrations

INITIAL_WELD_ID_KEYS = [
    ('U', 'Upstream'),
    ('D', 'Downstream'),
    ('C', 'Ceiling'),
    ('F', 'Floor'),
    ('L', 'Left Side'),
    ('R', 'Right Side'),
    ('S', 'Stiffener'),
    ('SP', 'Skin Plate'),
    ('SKP', 'Skirt Plate'),
    ('SB', 'Seal Bar'),
    ('SLP', 'Seal Plate'),
    ('BM', 'Base Material'),
    ('WW', 'Web Weld'),
    ('SMW', 'Seam Weld'),
    ('BUC', 'Blend Under Cut'),
    ('UC', 'Under Cut'),
    ('PW', 'Plate Weld'),
    ('P', 'Plate'),
    ('W', 'Web'),
    ('FP', 'Full Penetration'),
    ('VW', 'Vertical Weld'),
    ('BW', 'Beam Weld'),
    ('T', 'Top'),
    ('TW', 'Top Weld'),
    ('B', 'Bottom'),
    ('TG', 'To Gate'),
    ('FLG', 'Flange'),
    ('FW', 'Flange Weld'),
    ('TB', 'To Beam'),
    ('J', 'Joint'),
    ('E', 'End'),
    ('H', 'Horizontal'),
]


def seed_weld_id_keys(apps, schema_editor):
    WeldIdKey = apps.get_model('welds', 'WeldIdKey')
    for code, meaning in INITIAL_WELD_ID_KEYS:
        WeldIdKey.objects.get_or_create(code=code, defaults={'meaning': meaning})


def remove_weld_id_keys(apps, schema_editor):
    WeldIdKey = apps.get_model('welds', 'WeldIdKey')
    codes = [code for code, _ in INITIAL_WELD_ID_KEYS]
    WeldIdKey.objects.filter(code__in=codes).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('welds', '0005_weldidkey'),
    ]

    operations = [
        migrations.RunPython(seed_weld_id_keys, remove_weld_id_keys),
    ]
